### ISSUE TITLE
inversionefficiency

### ISSUE THREAD

**Issue by romainVala** [JosePMarques/MP2RAGE-related-scripts#2]
Hello
First thanks a lot for providing this useful piece of code.

I just notice the extra argument inversion efficiency was not taken into account in the function
T1M0estimaeMP2RAGE.m

I made a minor change : 
T1M0estimaeMP2RAGE linge 34:
if nargin==4

and also 
MP2RAGE_lookuptable. m ligne 50:
                        if nargin == 7

And then I could set the same default as Siemens (which takes in their application inversionefficiency to 1)

**Comment by JosePMarques** [comment]
Thanks for bringing this to my attention! I have made the changes you have mentioned to the code.

Yours,

Jose

**Comment by marcelzwiers** [comment]
@JosePMarques Perhaps you should then close this issue ;-)
